### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown pattern character 'Y'

### ISSUE THREAD

**Issue by pnjolapara** [anitaa1990/Github-Repo-Sample#1]
Just downloaded the source code, import it into the Android studio and run it Causing the error

08-16 16:12:46.053 1631-1652/? E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.an.github, PID: 1631
    java.lang.IllegalArgumentException: Unknown pattern character 'Y'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:305)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
        at com.an.github.utils.AppUtils$Companion.getLastWeekDate(AppUtils.kt:22)
        at com.an.github.datasource.GithubDataSource.loadInitial(GithubDataSource.kt:24)
        at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:323)
        at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:102)
        at androidx.paging.PagedList.create(PagedList.java:190)
        at androidx.paging.PagedList.access$000(PagedList.java:114)
        at androidx.paging.PagedList$Builder.build(PagedList.java:362)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:201)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:166)
        at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

After updating AppUtils.kt
getLastWeekDate-> date formate val df = SimpleDateFormat("yyyy-MM-dd") from "YYYY" to "yyyy"
it's working fine

**Comment by anitaa1990** [comment]
Ah ok. This might be cause I used Java 8 and this pattern is recognised in Java 8 but not in previous versions. I have updated the code to support previous versions of java. It should work now
